// Dil bağımsız katalog ilişkilerinin tek kaynağıdır.
// Çevrilen etiketler localization/translations/*/catalogs.json içindedir.

abstract final class CatalogStructure {
  static const Map<String, List<String>> nutrition = {
    'alcoholic_drinks': ['beer', 'cocktail', 'raki', 'wine', 'vodka'],
    'snacks_and_packaged_foods': [
      'biscuits',
      'chips',
      'granola_bar',
      'crackers',
      'popcorn',
    ],
    'spices_sauces_and_spicy_foods': [
      'chili_pepper',
      'hot_sauce',
      'black_pepper',
      'ketchup',
      'mayonnaise',
    ],
    'legumes': ['kidney_beans', 'peas', 'white_beans', 'lentils', 'chickpeas'],
    'fish_and_seafood': ['anchovies', 'shrimp', 'mussels', 'salmon', 'tuna'],
    'herbal_teas': [
      'sage_tea',
      'chamomile_tea',
      'fennel_tea',
      'linden_tea',
      'green_tea',
    ],
    'meat_and_poultry': ['beef', 'turkey', 'meatballs', 'lamb', 'chicken'],
    'fermented_pickled_smoked_and_processed_foods': [
      'smoked_meat',
      'kimchi',
      'salami',
      'sujuk',
      'pickles',
    ],
    'carbonated_and_acidic_drinks': [
      'soda_pop',
      'cola',
      'lemonade',
      'orange_juice',
      'sparkling_water',
    ],
    'gluten_grains_and_baked_foods': [
      'pastry',
      'bulgur',
      'bread',
      'pasta',
      'bagel',
    ],
    'gluten_free_grains_and_starches': [
      'basmati_rice',
      'brown_rice',
      'buckwheat',
      'quinoa',
      'corn',
      'potato',
      'rice',
      'rice_pilaf',
      'white_rice',
    ],
    'caffeinated_drinks': [
      'energy_drink',
      'espresso',
      'filter_coffee',
      'black_tea',
      'turkish_coffee',
    ],
    'mixed_dishes_and_ready_meals': [
      'doner',
      'hamburger',
      'instant_soup',
      'dumplings',
      'pizza',
    ],
    'nuts_and_seeds': [
      'sunflower_seeds',
      'almonds',
      'walnuts',
      'hazelnuts',
      'peanuts',
    ],
    'fruits': ['strawberries', 'apple', 'banana', 'orange', 'grapes'],
    'vegetables': ['broccoli', 'tomato', 'spinach', 'zucchini', 'cucumber'],
    'dairy_and_cheese': [
      'feta_cheese',
      'yellow_cheese',
      'kefir',
      'milk',
      'yogurt',
    ],
    'desserts_and_sugary_foods': [
      'baklava',
      'chocolate',
      'ice_cream',
      'cake',
      'candy',
    ],
    'fats_and_fried_foods': [
      'chicken_nuggets',
      'crispy_chicken',
      'fried_dough',
      'fried_chicken',
      'french_fries',
      'butter',
      'olive_oil',
    ],
    'eggs': ['boiled_egg', 'menemen', 'omelet', 'fried_egg', 'eggy_bread'],
  };

  static const Map<String, List<String>> medications = {
    'pain_fever_muscle_and_joint_medicines': [
      'pain_reliever_fever_reducer',
      'anti_inflammatory_pain_reliever',
      'muscle_relaxant',
    ],
    'stomach_and_bowel_medicines': [
      'acid_reducing_stomach_protecting_medicine',
      'nausea_vomiting',
      'bowel_regulators',
    ],
    'allergy_cold_and_respiratory_medicines': [
      'allergy_medicines',
      'nasal_medicines',
      'asthma_medicines_bronchodilators',
      'inhaled_corticosteroids',
    ],
    'infection_medicines': [
      'antibiotic',
      'antifungal',
      'antiviral',
      'antiparasitic',
    ],
    'blood_pressure_heart_and_edema_medicines': [
      'blood_pressure_medicine',
      'heart_rate_medicine',
      'diuretic',
      'heart_failure_medicine',
    ],
    'cholesterol_and_blood_thinning_medicines': [
      'cholesterol_medicine',
      'blood_thinner_clot_prevention',
    ],
    'diabetes_and_blood_sugar_medicines': [
      'tablet_oral_medicine',
      'glp_1_medicines',
      'insulins',
    ],
    'mental_health_and_sleep_medicines': [
      'antidepressant',
      'anxiety_medicine',
      'sleep_medicine_sedative',
      'antipsychotic',
    ],
    'migraine_epilepsy_and_nervous_system_medicines': [
      'migraine',
      'epilepsy_seizures',
      'nerve_pain',
      'parkinson_s',
    ],
    'hormone_thyroid_and_birth_control_medicines': [
      'thyroid_medicine',
      'birth_control',
      'progesterone',
      'estrogen_menopause_therapy',
    ],
  };

  static const Map<String, List<String>> medicationIngredients = {
    'pain_reliever_fever_reducer': [
      'paracetamol_acetaminophen',
      'ibuprofen',
      'naproxen',
      'diclofenac',
      'dexketoprofen',
      'ketoprofen',
      'meloxicam',
      'metamizole',
    ],
    'anti_inflammatory_pain_reliever': [
      'ibuprofen',
      'naproxen',
      'diclofenac',
      'dexketoprofen',
      'ketoprofen',
      'meloxicam',
    ],
    'muscle_relaxant': ['tizanidine', 'baclofen'],
    'acid_reducing_stomach_protecting_medicine': [
      'pantoprazole',
      'omeprazole',
      'esomeprazole',
      'lansoprazole',
      'famotidine',
      'calcium_carbonate',
      'sodium_alginate',
    ],
    'nausea_vomiting': ['metoclopramide', 'ondansetron', 'dimenhydrinate'],
    'bowel_regulators': [
      'lactulose',
      'macrogol_polyethylene_glycol',
      'bisacodyl',
      'loperamide',
    ],
    'allergy_medicines': [
      'cetirizine',
      'levocetirizine',
      'loratadine',
      'desloratadine',
      'fexofenadine',
    ],
    'nasal_medicines': ['budesonide', 'fluticasone'],
    'asthma_medicines_bronchodilators': [
      'salbutamol_albuterol',
      'budesonide',
      'fluticasone',
      'formoterol',
      'montelukast',
    ],
    'inhaled_corticosteroids': ['budesonide', 'fluticasone'],
    'antibiotic': [
      'amoxicillin',
      'amoxicillin_clavulanic_acid',
      'azithromycin',
      'clarithromycin',
      'cefuroxime',
      'ciprofloxacin',
      'doxycycline',
      'nitrofurantoin',
      'metronidazole',
    ],
    'antifungal': ['fluconazole'],
    'antiparasitic': ['metronidazole'],
    'blood_pressure_medicine': [
      'amlodipine',
      'losartan',
      'valsartan',
      'enalapril',
      'lisinopril',
      'metoprolol',
      'bisoprolol',
      'hydrochlorothiazide',
    ],
    'heart_rate_medicine': ['metoprolol', 'bisoprolol'],
    'diuretic': ['hydrochlorothiazide', 'furosemide', 'spironolactone'],
    'heart_failure_medicine': [
      'losartan',
      'valsartan',
      'enalapril',
      'lisinopril',
      'metoprolol',
      'bisoprolol',
      'furosemide',
      'spironolactone',
    ],
    'cholesterol_medicine': [
      'atorvastatin',
      'rosuvastatin',
      'simvastatin',
      'pravastatin',
      'ezetimibe',
    ],
    'blood_thinner_clot_prevention': [
      'aspirin',
      'clopidogrel',
      'apixaban',
      'rivaroxaban',
      'warfarin',
    ],
    'tablet_oral_medicine': [
      'metformin',
      'gliclazide',
      'sitagliptin',
      'empagliflozin',
      'dapagliflozin',
    ],
    'glp_1_medicines': ['semaglutide', 'liraglutide', 'dulaglutide'],
    'insulins': ['insulin_glargine', 'insulin_aspart'],
    'antidepressant': [
      'sertraline',
      'escitalopram',
      'fluoxetine',
      'venlafaxine',
      'duloxetine',
      'mirtazapine',
    ],
    'anxiety_medicine': ['alprazolam', 'diazepam', 'lorazepam'],
    'sleep_medicine_sedative': ['alprazolam', 'diazepam', 'lorazepam'],
    'antipsychotic': ['quetiapine'],
    'migraine': ['topiramate', 'sumatriptan', 'rizatriptan'],
    'epilepsy_seizures': [
      'pregabalin',
      'gabapentin',
      'levetiracetam',
      'lamotrigine',
      'valproate',
      'carbamazepine',
      'topiramate',
    ],
    'nerve_pain': ['pregabalin', 'gabapentin', 'carbamazepine'],
    'parkinson_s': ['levodopa_carbidopa'],
    'thyroid_medicine': ['levothyroxine', 'methimazole', 'carbimazole'],
    'birth_control': [
      'ethinylestradiol',
      'levonorgestrel',
      'drospirenone',
      'desogestrel',
      'etonogestrel',
    ],
    'progesterone': ['progesterone'],
    'estrogen_menopause_therapy': ['estradiol', 'progesterone'],
  };

  static const List<String> supplements = [
    'magnesium',
    'vitamin_d',
    'vitamin_b12',
    'vitamin_c',
    'multivitamin',
    'omega_3_fish_oil',
    'iron',
    'folic_acid_folate',
    'zinc',
    'calcium',
    'probiotic',
    'collagen',
    'biotin',
    'b_complex',
    'melatonin',
    'creatine',
    'protein_powder',
    'electrolyte',
    'coenzyme_q10_coq10',
    'ashwagandha',
    'st_john_s_wort',
    'andrographis',
    'astragalus_astragalus_root',
    'echinacea',
    'ginseng_panax_ginseng',
    'south_african_geranium_pelargonium_sidoides',
    'black_elderberry_sambucus_nigra',
    'cat_s_claw_uncaria_tomentosa',
    'garlic_extract',
    'siberian_ginseng_eleuthero',
    'green_tea_extract',
    'beta_glucan',
    'propolis',
    'reishi_shiitake_and_maitake_mushrooms',
    'turmeric_curcumin',
    'inositol',
    'vitamin_e',
    'vitamin_k_k2',
    'selenium',
  ];

  static const Map<String, List<String>> skincare = {
    'acne_oiliness_and_pores': [
      'azelaic_acid',
      'benzoyl_peroxide',
      'zinc',
      'niacinamide',
      'salicylic_acid',
      'sulfur',
    ],
    'exfoliation_and_texture': [
      'aha',
      'bha',
      'glycolic_acid',
      'lactic_acid',
      'pha',
    ],
    'sensitivity_and_soothing': [
      'allantoin',
      'cica_centella_asiatica',
      'propolis',
      'green_tea_extract',
    ],
    'pigmentation_and_uneven_tone': [
      'arbutin_alpha_arbutin',
      'vitamin_c',
      'kojic_acid',
      'licorice_root_extract',
      'rice_extract',
      'tranexamic_acid',
    ],
    'hydration_and_barrier': [
      'beta_glucan',
      'hyaluronic_acid',
      'panthenol',
      'ceramides',
      'squalane',
      'snail_mucin',
      'urea',
    ],
    'anti_aging_and_antioxidants': [
      'bakuchiol',
      'vitamin_e',
      'ferulic_acid',
      'peptides',
      'resveratrol',
      'retinol_retinal',
    ],
  };
}
