/// Dil bağımsız liste seçeneği aileleri.
enum OptionFamily {
  relationshipStatuses,
  chronicDiseases,
  womenDiseases,
  medicationTimes,
  stomachStates,
  moodOptions,
  moodCheckInOptions,
  moodCompanionOptions,
  moodPlaceOptions,
  sexualActivityOptions,
  sexualAfterFeelingOptions,
  nutritionMealOptions,
  nutritionQualityOptions,
  nutritionCravingOptions,
  nutritionFoodGroups,
  postMealFeelings,
  periodSymptomOptions,
  symptomSeverityOptions,
  symptomOverallOptions,
  symptomBodyOptions,
  symptomSkinHairOptions,
  symptomEnergyOptions,
  symptomSleepOptions,
  symptomDigestionOptions,
  flowOptions,
  dischargePresenceOptions,
  dischargeColors,
  dischargeConsistencies,
  dischargeAmounts,
  dischargeSymptoms,
  dosageOptions,
  shortWeekdays,
  weekdays,
  articleTopics,
  defaultMedications,
  defaultSupplements,
  calendarWeekdayInitials,
}

/// Her seçenek ailesindeki kararlı anahtarların görünüm sırasını tutar.
abstract final class OptionStructure {
  static const Map<OptionFamily, List<String>> keys = {
    OptionFamily.relationshipStatuses: [
      'single',
      'in_a_relationship',
      'married',
      'prefer_not_to_say',
    ],
    OptionFamily.chronicDiseases: [
      'type_1_diabetes',
      'type_2_diabetes',
      'hypertension',
      'asthma',
      'hypothyroidism',
      'hyperthyroidism',
      'heart_disease',
      'kidney_disease',
      'liver_disease',
      'anemia',
      'epilepsy',
      'depression',
      'anxiety_disorder',
      'migraine',
      'rheumatic_disease',
      'high_cholesterol',
    ],
    OptionFamily.womenDiseases: [
      'dysmenorrhea_painful_periods',
      'pcos_polycystic_ovary_syndrome',
      'endometriosis',
      'adenomyosis',
      'fibroids',
      'ovarian_cyst',
      'irregular_periods',
      'amenorrhea',
      'pms_premenstrual_syndrome',
      'pelvic_inflammatory_disease',
      'hpv',
      'recurrent_vaginal_infection',
      'vulvodynia',
      'vaginismus',
    ],
    OptionFamily.medicationTimes: ['morning', 'noon', 'evening'],
    OptionFamily.stomachStates: ['empty_stomach', 'with_food'],
    OptionFamily.moodOptions: [
      'angry',
      'good',
      'low',
      'happy',
      'calm',
      'tired',
      'energetic',
    ],
    OptionFamily.moodCheckInOptions: [
      'low',
      'sensitive',
      'neutral',
      'good',
      'great',
    ],
    OptionFamily.moodCompanionOptions: [
      'by_myself',
      'with_my_partner',
      'with_friends',
      'with_family',
      'with_co_workers',
    ],
    OptionFamily.moodPlaceOptions: [
      'at_home',
      'at_work',
      'outside',
      'in_transit',
      'social',
    ],
    OptionFamily.sexualActivityOptions: [
      'with_a_partner',
      'masturbation',
      'protected',
      'unprotected',
      'no_activity',
    ],
    OptionFamily.sexualAfterFeelingOptions: [
      'comfortable',
      'connected',
      'calm',
      'energized',
      'neutral',
      'tired',
      'sensitive',
      'uncomfortable',
      'pain',
    ],
    OptionFamily.nutritionMealOptions: [
      'breakfast',
      'lunch',
      'dinner',
      'snack',
    ],
    OptionFamily.nutritionQualityOptions: ['light', 'medium', 'heavy'],
    OptionFamily.nutritionCravingOptions: [
      'sweet',
      'salty',
      'chocolate',
      'carbs',
      'spicy',
      'caffeine',
      'nothing',
    ],
    OptionFamily.nutritionFoodGroups: [
      'gluten',
      'wheat',
      'dairy',
      'lactose_containing',
      'eggs',
      'nuts',
      'peanuts',
      'soy',
      'sesame',
      'legumes',
      'red_meat',
      'poultry',
      'fish',
      'crustacean_shellfish',
      'vegetables',
      'fruit',
      'onion_garlic',
      'processed_food',
      'spicy_food',
      'high_fat_fried',
      'artificially_sweetened',
      'caffeinated',
    ],
    OptionFamily.postMealFeelings: [
      'comfortable',
      'energetic',
      'full',
      'bloated',
      'tired',
      'nauseous',
      'gassy',
      'reflux',
      'still_hungry',
    ],
    OptionFamily.periodSymptomOptions: [
      'cramps',
      'lower_back_pain',
      'headache',
      'bloating',
      'fatigue',
      'clots',
    ],
    OptionFamily.symptomSeverityOptions: ['mild', 'moderate', 'strong'],
    OptionFamily.symptomOverallOptions: [
      'feeling_good',
      'stressed',
      'happy',
      'calm',
      'motivated',
      'anxious',
      'restless',
      'irritable',
      'sad',
      'experiencing_mood_swings',
    ],
    OptionFamily.symptomBodyOptions: [
      'cramps',
      'headache',
      'lower_back_pain',
      'breast_tenderness',
      'upper_mid_back_pain',
      'joint_muscle_pain',
      'dizziness',
      'frequent_urination',
    ],
    OptionFamily.symptomSkinHairOptions: [
      'acne',
      'dry_skin',
      'oily_skin',
      'sensitive_skin',
      'skin_redness',
      'itchy_skin',
      'oily_hair',
      'dry_hair',
      'hair_loss',
      'brittle_nails',
    ],
    OptionFamily.symptomEnergyOptions: [
      'energetic',
      'fatigue',
      'focused',
      'brain_fog',
      'forgetful',
    ],
    OptionFamily.symptomSleepOptions: [
      'slept_well',
      'slept_fairly_well',
      'slept_poorly',
      'trouble_falling_asleep',
      'woke_often',
      'woke_up_energized',
      'woke_up_rested',
      'woke_up_sleepy_tired',
      'woke_up_with_a_headache',
      'woke_up_early',
      'vivid_dreams',
      'nightmare',
    ],
    OptionFamily.symptomDigestionOptions: [
      'digestion_feels_good_and_regular',
      'cravings',
      'increased_decreased_appetite',
      'nausea',
      'constipation',
      'diarrhea',
      'bloating',
      'gas',
      'reflux',
    ],
    OptionFamily.flowOptions: ['spotting', 'light', 'medium', 'heavy'],
    OptionFamily.dischargePresenceOptions: ['present', 'none'],
    OptionFamily.dischargeColors: [
      'clear',
      'white',
      'cream',
      'yellow',
      'green',
      'gray',
      'brown',
      'pink',
      'red_blood_tinged',
      'other',
    ],
    OptionFamily.dischargeConsistencies: [
      'watery',
      'slippery',
      'stretchy_egg_white_like',
      'creamy',
      'sticky',
      'thick_clumpy',
      'frothy',
      'other',
    ],
    OptionFamily.dischargeAmounts: ['light', 'moderate', 'heavy'],
    OptionFamily.dischargeSymptoms: [
      'unusual_odor',
      'itching',
      'burning',
      'painful_urination',
      'pelvic_lower_abdominal_pain',
    ],
    OptionFamily.dosageOptions: [
      '1_count',
      '2_count',
      '3_count',
      '4_count',
      '5_count',
      '6_count',
    ],
    OptionFamily.shortWeekdays: [
      'mon',
      'tue',
      'wed',
      'thu',
      'fri',
      'sat',
      'sun',
    ],
    OptionFamily.weekdays: [
      'monday',
      'tuesday',
      'wednesday',
      'thursday',
      'friday',
      'saturday',
      'sunday',
    ],
    OptionFamily.articleTopics: [
      'nutrition',
      'exercise',
      'womens_health',
      'mood',
      'sleep',
      'general_health',
    ],
    OptionFamily.defaultMedications: [
      'parol',
      'aspirin',
      'arveles',
      'majezik',
      'minoset',
    ],
    OptionFamily.defaultSupplements: [
      'magnesium',
      'vitamin_d',
      'omega_3',
      'iron',
      'vitamin_b12',
      'vitamin_c',
      'zinc',
    ],
    OptionFamily.calendarWeekdayInitials: [
      'm',
      't',
      'w',
      't_2',
      'f',
      's',
      's_2',
    ],
  };
}
